version: '3'
services:

  #PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel


  #Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


    depends_on:
      - php
      - mysql
    networks:
      - laravel
 

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

#Docker Networks
networks:
  laravel:
     driver: bridge

#Volumes
volumes:
  dbdata:
     driver: local